name: Docker build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build amd64 image
        uses: docker/build-push-action@v4
        id: docker_build_amd64
        with:
          context: .
          platforms: amd64
          cache-from: type=gha
          cache-to: type=gha
          load: true
      - name: Build arm64 image
        uses: docker/build-push-action@v4
        id: docker_build_arm64
        with:
          context: .
          platforms: arm64
          cache-from: type=gha
          cache-to: type=gha
          load: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name == 'push'
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fishnet-builder
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
        if: github.event_name == 'push'
      - name: Docker push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux,arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: github.event_name == 'push'
